# logo3dprint - SVG logo to multi-colour 3D print model
#
# Requires SDL3 (pkg-config "sdl3"). Nuklear and libtess2 are vendored.
#   make            build ./logo3dprint
#   make test       run the headless export tests
#   make clean
#   make release VERSION=v1.2.3   tag and push a release (see below)

CC      ?= cc
CFLAGS  ?= -O2 -g
CSTD     = -std=c99
WARN     = -Wall -Wextra -Wno-unused-parameter
DEFS     = -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE
SDL_CFLAGS ?= $(shell pkg-config --cflags sdl3)
SDL_LIBS   ?= $(shell pkg-config --libs sdl3)
INCLUDES = -Isrc -Ithird_party/libtess2 -Ithird_party/nuklear -Ithird_party/stb

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
  PLATFORM_LIBS = -lm
else
  PLATFORM_LIBS = -lm -ldl
endif

CORE_SRC = src/xml.c src/svg.c src/region.c src/model.c src/zip.c \
           src/export_stl.c src/export_3mf.c src/app.c src/cli.c src/textfont.c
GUI_SRC  = src/main.c src/gui.c src/render.c src/glapi.c src/nk_sdl_gl3.c
NK_SRC   = src/nk_impl.c
TESS_SRC = $(wildcard third_party/libtess2/*.c)

BUILD    = build
CORE_OBJ = $(patsubst src/%.c,$(BUILD)/%.o,$(CORE_SRC))
GUI_OBJ  = $(patsubst src/%.c,$(BUILD)/%.o,$(GUI_SRC))
NK_OBJ   = $(patsubst src/%.c,$(BUILD)/%.o,$(NK_SRC))
TESS_OBJ = $(patsubst third_party/libtess2/%.c,$(BUILD)/tess2_%.o,$(TESS_SRC))

all: logo3dprint

logo3dprint: $(CORE_OBJ) $(GUI_OBJ) $(NK_OBJ) $(TESS_OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(SDL_LIBS) $(PLATFORM_LIBS)

$(BUILD)/%.o: src/%.c | $(BUILD)
	$(CC) $(CSTD) $(CFLAGS) $(WARN) $(DEFS) $(INCLUDES) $(SDL_CFLAGS) -MMD -MP -c -o $@ $<

# stb_truetype is compiled static; its unused helpers would warn.
$(BUILD)/textfont.o: src/textfont.c | $(BUILD)
	$(CC) $(CSTD) $(CFLAGS) $(WARN) -Wno-unused-function $(DEFS) $(INCLUDES) $(SDL_CFLAGS) -MMD -MP -c -o $@ $<

# Nuklear's implementation is noisy under -Wextra; build it without warnings.
$(BUILD)/nk_impl.o: src/nk_impl.c | $(BUILD)
	$(CC) $(CSTD) $(CFLAGS) -w $(DEFS) $(INCLUDES) $(SDL_CFLAGS) -MMD -MP -c -o $@ $<

# header dependencies generated by -MMD
-include $(CORE_OBJ:.o=.d) $(GUI_OBJ:.o=.d) $(NK_OBJ:.o=.d)

$(BUILD)/tess2_%.o: third_party/libtess2/%.c | $(BUILD)
	$(CC) $(CFLAGS) -w -DNDEBUG -Ithird_party/libtess2 -c -o $@ $<

$(BUILD):
	mkdir -p $(BUILD)

test: logo3dprint
	sh tests/run_tests.sh ./logo3dprint

clean:
	rm -rf $(BUILD) logo3dprint

# Tags and pushes a release; .github/workflows/release.yml then builds
# Linux/Windows/macOS binaries and publishes them to a GitHub Release.
release:
	@test -n "$(VERSION)" || { echo "Usage: make release VERSION=v1.2.3" >&2; exit 1; }
	@echo "$(VERSION)" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$$' || \
		{ echo "VERSION must look like v1.2.3, got '$(VERSION)'" >&2; exit 1; }
	@git diff --quiet && git diff --cached --quiet || \
		{ echo "Working tree not clean, commit or stash first" >&2; exit 1; }
	git tag -a "$(VERSION)" -m "$(VERSION)"
	git push origin "$(VERSION)"

.PHONY: all clean test release
