#!/usr/bin/env python3
"""Regenerate src/icon_data.h from assets/logo3dprint.ico.

The window icon is compiled into the program (no image library, no file to
find at run time) as a run-length encoded RGBA stream: records of
[count, r, g, b, a], top row first. Needs Pillow:

    python3 tools/mkicon.py
"""
import os, sys
from PIL import Image

here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, "..", "assets", "logo3dprint.ico")
dst = os.path.join(here, "..", "src", "icon_data.h")

im = Image.open(src)
if hasattr(im, "ico"):
    im = im.ico.getimage(max(im.ico.sizes()))   # the largest image in the .ico
im = im.convert("RGBA")
w, h = im.size
px = list(im.getdata())

runs = []
for p in px:
    if runs and runs[-1][1] == p and runs[-1][0] < 255:
        runs[-1][0] += 1
    else:
        runs.append([1, p])

with open(dst, "w") as f:
    f.write("/* Generated by tools/mkicon.py from assets/logo3dprint.ico; do not edit.\n"
            " * Run-length encoded RGBA: [count, r, g, b, a] records, top row first. */\n")
    f.write(f"#define ICON_W {w}\n#define ICON_H {h}\n")
    f.write("static const unsigned char icon_rle[] = {\n")
    line = []
    for n, (r, g, b, a) in runs:
        line.append(f"{n},{r},{g},{b},{a}")
        if len(line) == 12:
            f.write("    " + ",".join(line) + ",\n")
            line = []
    if line:
        f.write("    " + ",".join(line) + ",\n")
    f.write("};\n")
print(f"{dst}: {w}x{h}, {len(runs)} runs, {len(runs) * 5} bytes")
